
import re
import time
from pathlib import Path
from utils import SECRETS_DIR

def get_input(prompt_text):

    try:
        return input(prompt_text).strip()
    except EOFError:
        return ""

def create_cookie_line(domain, name, value, expire_timestamp):

    include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
    secure = "TRUE"
    path = "/"
    return f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expire_timestamp}\t{name}\t{value}\n"

def _update_config_cookies_path(cookie_file_path: Path):

    secrets_path = SECRETS_DIR / ".secrets.yaml"


    path_str = str(cookie_file_path.resolve().as_posix())

    if secrets_path.exists():
        with open(secrets_path, 'r', encoding='utf-8') as f:
            content = f.read()

        new_content = re.sub(
            r'cookies_path:\s*".*"',
            f'cookies_path: "{path_str}"',
            content
        )
        if new_content == content:
            new_content = re.sub(
                r'cookies_path:\s*.*',
                f'cookies_path: "{path_str}"',
                content
            )
    else:

        new_content = (
            "# LIZ Secrets - Sensitive credentials\n"
            "# This file contains sensitive credentials. Do not share it.\n\n"
            f'cookies_path: "{path_str}"\n'
        )

    with open(secrets_path, 'w', encoding='utf-8') as f:
        f.write(new_content)

    return True

def run_builder():

    print("\nYa LIZ Manual Cookie Builder Ya")
    print("---------------------------------")
    print("This tool will guide you to extract the exact session cookies needed")
    print("from your trusted browser, without relying on sketchy extensions.\n")

    one_year_from_now = int(time.time()) + (365 * 24 * 60 * 60)

    cookies_content = "# Netscape HTTP Cookie File\n"
    cookies_content += "# Generated by LIZ Cookie Builder\n"
    cookies_content += "# This is a generated file!  Do not edit.\n\n"

    print("Y Setup: X / Twitter")
    print("  1. Open your normal web browser and log in to x.com")
    print("  2. Press F12 to open Developer Tools")
    print("  3. Go to the 'Application' tab (Chrome/Edge) or 'Storage' tab (Firefox)")
    print("  4. Expand 'Cookies' on the left side and click 'https://x.com'")
    print("  5. Find the row named 'auth_token' and copy its 'Value'")

    x_token = get_input("\n  Paste the 'auth_token' value here (or press Enter to skip X): ")
    if x_token:

        cookies_content += create_cookie_line(".twitter.com", "auth_token", x_token, one_year_from_now)
        cookies_content += create_cookie_line(".x.com", "auth_token", x_token, one_year_from_now)
        print("  [OK] X/Twitter authentication added.\n")
    else:
        print("  ai  Skipping X/Twitter.\n")

    print("Y  Setup: Instagram")
    print("  1. Open your normal web browser and log in to instagram.com")
    print("  2. Press F12 to open Developer Tools")
    print("  3. Go to the 'Application' tab (Chrome/Edge) or 'Storage' tab (Firefox)")
    print("  4. Expand 'Cookies' on the left side and click 'https://www.instagram.com'")
    print("  5. Find the row named 'sessionid' and copy its 'Value'")

    ig_token = get_input("\n  Paste the 'sessionid' value here (or press Enter to skip Instagram): ")
    if ig_token:
        cookies_content += create_cookie_line(".instagram.com", "sessionid", ig_token, one_year_from_now)
        print("  [OK] Instagram authentication added.\n")
    else:
        print("  ai  Skipping Instagram.\n")

    if not x_token and not ig_token:
        print("[ERROR] No cookies provided. Exiting.")
        return

    cookie_file_path = SECRETS_DIR / "cookies.txt"

    try:
        with open(cookie_file_path, "w", encoding="utf-8") as f:
            f.write(cookies_content)
        print(f"YZ Success! Secure cookies file generated at: {cookie_file_path}")
    except Exception as e:
        print(f"[ERROR] Failed to write cookies.txt: {e}")
        return

    try:
        if _update_config_cookies_path(cookie_file_path):
            print(f"[OK] Updated .secrets.yaml to use the new cookies.txt")
        print("\nY IMPORTANT: Do not share your cookies.txt file! It contains your active login sessions.")
    except Exception as e:
        print(f"as i  Generated cookies.txt, but failed to update .secrets.yaml: {e}")
        print(f"   Please manually add the path to your config.yaml: cookies_path: '{cookie_file_path.absolute()}'")

if __name__ == "__main__":
    run_builder()
